/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include <stdio.h>

IfxCpu_syncEvent g_cpuSyncEvent = 0;

unsigned int
cal_checksum(unsigned int* m, unsigned int size) {
    unsigned int checksum = 0;
    for(unsigned int i=0; i<size; i++) {
        checksum += *(m+i);
    }
    return checksum;
}

void abnormal_access() {
    unsigned char* p = (unsigned char*)0x700195F0;
    *(p+0) = 0xCD;
    *(p+3) = 0x4A;

}

int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    // important memory segment containing control parameter
    unsigned int table[4] = { 0, 0, 0, 0 };

    // determined parameters (heavy calculation result)
    table[0] = 0x12345678;
    table[1] = 0xAABBCCDD;
    table[2] = 0x00000000;
    table[3] = 0x5ABBEEFF;

    // check sum preparation on stable time
    unsigned int org_checksum = 0;

    // start address to verify , and size
    org_checksum = cal_checksum(0x80000000, 1024*8);

    printf("checksum in protection region: 0x%08X\n", org_checksum);

    // abnormal access
    abnormal_access();

    unsigned int live_checksum;
    live_checksum = cal_checksum(&table[0], 4);
    printf("checksum in safe region: 0x%08X\n", live_checksum);

    if (live_checksum != org_checksum) {
        printf("stack frame is contaminated, please go into emergency mode\n");
    }

    while(1)
    {
    }
    return (1);
}
