/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include <stdio.h>

IfxCpu_syncEvent g_cpuSyncEvent = 0;


void func1(void) {
    volatile unsigned int a = 0x5AFF7801;
    printf("func1 is called\n");
    printf("a in func1 : 0x%08x\n", a);

}

void func2(void) {
    volatile unsigned int a = 0xFFBBCCDD;
    printf("func2 is called\n");
    printf("a in func2 : 0x%08x\n", a);
}


int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);


    unsigned int a = 0x12345678;

    // data pointer to point out a region in data memory (sram)
    unsigned int* p = &a;
    printf("a's address is %p\n", p);


    // variable containing an address
    //   to point out function body in code memory (flash)
    // we say function pointer;
    void (* volatile callback)(void);

    // callback variable is allocated in sram data memory
    // so we can overwrite func pointer with address of specific function .
    callback = func1;
    printf("address to jump : 0x%p\n", callback);

    // callback() can be redirected to user specific function.
    callback();
    
    // modify function pointer's value with new function start
    callback = func2;
    // after above line, force overwrite with func1 address (0x8000029C) in memory windows
    printf("address to jump : 0x%p\n", callback);
    callback();


    printf("a is still 0x%08X\n", a);


    while(1)
    {
    }
    return (1);
}
